//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prim2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пример.
    /// </summary>
    // *** Start programmer edit section *** (Пример CustomAttributes)

    // *** End programmer edit section *** (Пример CustomAttributes)
    [AutoAltered()]
    [Caption("Проба")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПримерE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ПримерL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Пример : ICSSoft.STORMNET.DataObject
    {
        
        private int fНаименование;
        
        // *** Start programmer edit section *** (Пример CustomMembers)

        // *** End programmer edit section *** (Пример CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Пример.Наименование CustomAttributes)

        // *** End programmer edit section *** (Пример.Наименование CustomAttributes)
        public virtual int Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Пример.Наименование Get start)

                // *** End programmer edit section *** (Пример.Наименование Get start)
                int result = this.fНаименование;
                // *** Start programmer edit section *** (Пример.Наименование Get end)

                // *** End programmer edit section *** (Пример.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пример.Наименование Set start)

                // *** End programmer edit section *** (Пример.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Пример.Наименование Set end)

                // *** End programmer edit section *** (Пример.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПримерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПримерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПримерE", typeof(IIS.Prim2.Пример));
                }
            }
            
            /// <summary>
            /// "ПримерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПримерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПримерL", typeof(IIS.Prim2.Пример));
                }
            }
        }
    }
}
